GCW_INSTANCE=DEV
GCW_UI_TERMINAL_FONT_FAMILY='NanumGothicCoding', 'NanumGothic Coding', monospace
GCW_UI_OPT_CMDC_TO_CTRLC=true
GCW_UI_OPT_CMDY_TO_CTRLY=true
GCW_UI_CUSTOM_SHORTCUT={"metaKey":true,"ctrlKey":false,"altKey":false,"shiftKey":true,"key":"z"}
GCW_UI_OPT_MAP_HOME=true
GCW_UI_OPT_MAP_END=true
GCW_UI_FILE_TREE_STYLE=2
GCW_UI_TERMINAL_FONT_SIZE=17