HOME=/home/jerryj
GIT=/home/jerryj/git
PERSONAL=/opt/jerrydisk/git/personal
QNA=/opt/jerrydisk/git/personal/All_QnA
BUSINESS=/opt/jerrydisk/git/business
FITNESS=/opt/jerrydisk/git/personal/202603f-Fitness
SUNWOO=/home/jerryj/git/personal/202603s-Sunwoo-Webtoon-grow
JIWOO=/home/jerryj/git/personal/202603j-Jiwoo-Boyfriend
TELEGRAM=/opt/jerrydisk/git/personal/202603f-Fitness/telegram-gcw-bot
